In [1]:
import numpy as np
import numpy.linalg as LA

In [2]:
def power_method(A, x, n=1, print_everything = True, rayleigh = False):
    '''Power method for computation of maximum abs(lambda)
        
        Input:
            A nxn matrix
            x starting nx1 vector (x_0)
            n = 1 (default) the maximum number of iterations
            print_everything = True (default) prints status of method in every iteration
            rayleigh = False (default) if True, algorithm uses the Rayleigh quotient for eigenvalue approximation
        
        Output:
            x normalized eigenvector approximation at the n-iteration
            v the eigenvalue approximation at the n-iternation for rayleigh method 
              and len(x) values computed, that all converge to lambda_max as n--> infty
    '''
    for k in range(n):
        x_old = np.copy(x)
        y = np.matmul(A,x)
        norm_y = LA.norm(y)
        x = (1./norm_y)*y
        if rayleigh:
            Ax = np.matmul(A,x)
            v = np.matmul(x,Ax)
        else:       
            v = []
            for i in range(len(x)):
                if np.abs(x_old[i])<1e-10: continue 
                v.append(y[i]/x_old[i])
        if print_everything: print_power_meth_status(k,x,v,rayleigh)
    return x, v

def print_power_meth_status(k,x,v,rayleigh):
    print("iteration: ", k+1)
    print("eigenvector: ", x)
    if rayleigh:
        print("eigenvalue: ", v)
    else:
        print("eigenvalue: ") 
        for v_k in v:
            print(v_k)
    print("")

In [3]:
#compute matrix A1 = A - lambda_1 u1 u1^T
A = np.array([[12,2,-1],
             [2,12,2],
             [-1,2,12]])
x0 = np.float64(np.array([1,0,0]))
eigenvect1, eigenval1 = power_method(A,x0,n=200,print_everything = False)
print(eigenvect1)
print(eigenval1)
u1u1T = [ [ eigenvect1[i] *eigenvect1[j] for j in range(len(eigenvect1))] for i in range(len(eigenvect1))]
A_1 = A - np.multiply(eigenval1,u1u1T)
A_1

[0.45440135 0.76618459 0.45440135]
[14.372281316211613, 14.372281323269014, 14.372281330326414]


array([[ 9.0324029 , -3.00378611, -3.96759707],
       [-3.00378611,  3.56291282, -3.00378607],
       [-3.96759707, -3.00378606,  9.03240296]])

In [4]:
# Eigenvalues for A and A_1
v,w = LA.eigh(A)
print(v)
v1, w1 = LA.eigh(A_1)
v1

[ 8.62771868 13.         14.37228132]


array([2.31266014e-09, 8.62771868e+00, 1.30000000e+01])

In [5]:
eigenvect2, eigenval2 = power_method(A_1,x0,n=5,print_everything = True, rayleigh = False)

iteration:  1
eigenvector:  [ 0.87586442 -0.29127458 -0.38473451]
eigenvalue: 
9.032402903903364

iteration:  2
eigenvector:  [ 0.84321904 -0.20548141 -0.49674847]
eigenvalue: 
11.774149232283703
8.62771870703557
15.790701233755586

iteration:  3
eigenvector:  [ 0.80842012 -0.14044865 -0.57160395]
eigenvalue: 
12.101735899990837
8.627718722393071
14.524782515939147

iteration:  4
eigenvector:  [ 0.77907792 -0.09448285 -0.61976656]
eigenvalue: 
12.359598489313266
8.627718745533313
13.90572059005253

iteration:  5
eigenvector:  [ 0.75687877 -0.0630882  -0.6505032 ]
eigenvalue: 
12.552962494765822
8.62771878040036
13.561948760590372



In [6]:
eigenvect2_rayl, eigenval2_rayl = power_method(A_1,x0,n=5,print_everything = True, rayleigh = True)

iteration:  1
eigenvector:  [ 0.87586442 -0.29127458 -0.38473451]
eigenvalue:  12.10173589983083

iteration:  2
eigenvector:  [ 0.84321904 -0.20548141 -0.49674847]
eigenvalue:  12.552962494675851

iteration:  3
eigenvector:  [ 0.80842012 -0.14044865 -0.57160395]
eigenvalue:  12.791150231264968

iteration:  4
eigenvector:  [ 0.77907792 -0.09448285 -0.61976656]
eigenvalue:  12.905484119659306

iteration:  5
eigenvector:  [ 0.75687877 -0.0630882  -0.6505032 ]
eigenvalue:  12.957859942136988



In [7]:
eigenvect2, eigenval2 = power_method(A_1,x0,n=100,print_everything = False, rayleigh = False)
eigenvect2_rayl, eigenval2_rayl = power_method(A_1,x0,n=18,print_everything = False, rayleigh = True)
print("Power method:", eigenval2)
print("using Rayleigh:", eigenval2_rayl)

Power method: [13.0, 13.0, 13.0]
using Rayleigh: 12.99999900076125
