In [4]:
import numpy as np
import numpy.linalg as LA

In [5]:
A = np.array([[12,2,-1],
             [2,12,2],
             [-1,2,12]])
eigenvalues, eigenvectors = np.linalg.eigh(A)
print(eigenvalues)
print(eigenvectors)
eigenvalues.max()

[ 8.62771868 13.         14.37228132]
[[ 5.41774320e-01  7.07106781e-01 -4.54401349e-01]
 [-6.42620551e-01 -1.11022302e-15 -7.66184591e-01]
 [ 5.41774320e-01 -7.07106781e-01 -4.54401349e-01]]


14.372281323269013

In [12]:
def power_method(A, x, n=1, print_everything = True, rayleigh = False):
    '''Power method for computation of maximum abs(lambda)
        
        Input:
            A nxn matrix
            x starting nx1 vector (x_0)
            n = 1 (default) the maximum number of iterations
            print_everything = True (default) prints status of method in every iteration
            rayleigh = False (default) if True, algorithm uses the Rayleigh quotient for eigenvalue approximation
        
        Output:
            x normalized eigenvector approximation at the n-iteration
            v the eigenvalue approximation at the n-iternation
    '''
    norm_x = LA.norm(x)
    for k in range(n):
        y = np.matmul(A,x)
        norm_y = LA.norm(y)
        x = (1./norm_y)*y
        if rayleigh:
            Ax = np.matmul(A,x)
            norm_x_A = np.matmul(x,Ax)
            norm_x_2 = LA.norm(x) 
            v = norm_x_A / np.square(norm_x_2)
        else:        
            v = norm_y/norm_x
        norm_x = np.linalg.norm(x, np.inf)
        
        if print_everything:
            print_power_meth_status(k,x,v)
    return x, v

def print_power_meth_status(k,x,v):
    print("iteration: ", k+1)
    print("eigenvector: ", x)
    print("eigenvalue: ", v)
    print("")

In [13]:
x0 = np.float64(np.array([1,0,0]))
eigenvect, eigenval = power_method(A,x0,n=3,print_everything = True)

iteration:  1
eigenvector:  [ 0.9830783   0.16384638 -0.08192319]
eigenvalue:  12.206555615733702

iteration:  2
eigenvector:  [ 0.94773821  0.29259032 -0.12721318]
eigenvalue:  13.101367613090373

iteration:  3
eigenvector:  [ 0.91052941  0.38817306 -0.14233012]
eigenvalue:  14.004685298350765



In [14]:
#check that A*v = lambda*v and print lambda
print(np.matmul(A,eigenvect))
print(eigenval*eigenvect)
eigenval

[11.84502918  6.19447535 -1.84214477]
[12.75167785  5.43624161 -1.99328859]


14.004685298350765

In [15]:
# more iterations to get a better approximation
eigenvect, eigenval = power_method(A,x0,n=14,print_everything = True)

iteration:  1
eigenvector:  [ 0.9830783   0.16384638 -0.08192319]
eigenvalue:  12.206555615733702

iteration:  2
eigenvector:  [ 0.94773821  0.29259032 -0.12721318]
eigenvalue:  13.101367613090373

iteration:  3
eigenvector:  [ 0.91052941  0.38817306 -0.14233012]
eigenvalue:  14.004685298350765

iteration:  4
eigenvector:  [ 0.87784381  0.45907712 -0.1365227 ]
eigenvalue:  14.819205000340109

iteration:  5
eigenvector:  [ 0.85033627  0.51301102 -0.11725155]
eigenvalue:  15.524964452168241

iteration:  6
eigenvector:  [ 0.82675883  0.55535681 -0.08971425]
eigenvalue:  16.140735810493123

iteration:  7
eigenvector:  [ 0.80567594  0.58956703 -0.0574194 ]
eigenvalue:  16.696500245807222

iteration:  8
eigenvector:  [ 0.785997    0.61781173 -0.0227463 ]
eigenvalue:  17.219916337963912

iteration:  9
eigenvector:  [0.76704222 0.64147139 0.01267632]
eigenvalue:  17.73172981145456

iteration:  10
eigenvector:  [0.74846371 0.66145573 0.04773239]
eigenvalue:  18.245451063256453

iteration:  11
e

In [7]:
# second largest lambda
u1u1T = [ [ eigenvect[i] *eigenvect[j] for j in range(len(eigenvect))] for i in range(len(eigenvect))]
u1u1T

[[0.8965997462830562, 0.946889511127384, 0.22869249697229743],
 [0.946889511127384, 1.0, 0.2415197277874712],
 [0.22869249697229743, 0.2415197277874712, 0.058331778910534184]]

In [8]:
np.multiply(eigenval,u1u1T)

array([[12.89296395, 13.6161229 ,  3.2885623 ],
       [13.6161229 , 14.37984341,  3.47301587],
       [ 3.2885623 ,  3.47301587,  0.83880185]])

In [9]:
A_1 = A - np.multiply(eigenval,u1u1T)
A_1

array([[ -0.89296395, -11.6161229 ,  -4.2885623 ],
       [-11.6161229 ,  -2.37984341,  -1.47301587],
       [ -4.2885623 ,  -1.47301587,  11.16119815]])

In [10]:
x0 = np.float64(np.array([1,0,0]))
eigenvect2, eigenval2 = power_method(A_1,x0,n=13,print_everything = False)
eigenval2

13.027618426068742

In [11]:
x0 = np.float64(np.array([1,0,0]))
eigenvect, eigenval = power_method(A,x0,n=5,print_everything = True)

iteration:  1
eigenvector:  [ 1.          0.16666667 -0.08333333]
eigenvalue:  12.0

iteration:  2
eigenvector:  [ 1.          0.30872483 -0.13422819]
eigenvalue:  12.416666666666668

iteration:  3
eigenvector:  [ 1.          0.42631579 -0.15631579]
eigenvalue:  12.751677852348994

iteration:  4
eigenvector:  [ 1.          0.52295991 -0.15552049]
eigenvalue:  13.008947368421053

iteration:  5
eigenvector:  [ 1.          0.60330371 -0.13788845]
eigenvalue:  13.201440304244043



In [12]:
eigenvect, eigenval = power_method(A,x0,n=5,print_everything = True, rayleigh=True)

iteration:  1
eigenvector:  [ 1.          0.16666667 -0.08333333]
eigenvalue:  12.751677852348994

iteration:  2
eigenvector:  [ 1.          0.30872483 -0.13422819]
eigenvalue:  13.201440304244047

iteration:  3
eigenvector:  [ 1.          0.42631579 -0.15631579]
eigenvalue:  13.451968613159979

iteration:  4
eigenvector:  [ 1.          0.52295991 -0.15552049]
eigenvalue:  13.600985441880505

iteration:  5
eigenvector:  [ 1.          0.60330371 -0.13788845]
eigenvalue:  13.703728651256876



In [13]:
eigenvalues

array([ 8.62771868, 13.        , 14.37228132])