In [1]:
import numpy as np
import numpy.linalg as LA

In [2]:
A = np.array([[12,2,-1],
             [2,12,2],
             [-1,2,12]])
eigenvalues, eigenvectors = LA.eigh(A)
print(eigenvalues)
print(eigenvectors)
eigenvalues.max()

[ 8.62771868 13.         14.37228132]
[[ 5.41774320e-01  7.07106781e-01 -4.54401349e-01]
 [-6.42620551e-01 -1.11022302e-15 -7.66184591e-01]
 [ 5.41774320e-01 -7.07106781e-01 -4.54401349e-01]]


14.372281323269013

In [3]:
def power_method(A, x, n=1, print_everything = True):
    '''Power method for computation of maximum abs(lambda)
        
        Input:
            A nxn matrix
            x starting nx1 vector (x_0)
            n = 1 (default) the maximum number of iterations
            print_everything = True (default) prints status of method in every iteration
        
        Output:
            x normalized eigenvector approximation at the n-iteration
            vs the eigenvalue approximations at the n-iternation (len(x) values computed, that all converge to lambda_max as n--> infty)
    '''
    for k in range(n):
        y = np.matmul(A,x)
        norm_y = LA.norm(y)
        vs = []
        for i in range(len(x)):
            if np.abs(x[i])<1e-10: continue 
            vs.append(y[i]/x[i])
        x = (1./norm_y)*y  
        if print_everything: print_power_meth_status(k,x,vs)
    return x, vs

def print_power_meth_status(k,x,vs):
    print("iteration: ", k+1)
    print("eigenvector: ", x)
    print("eigenvalue: ") 
    for v in vs:
        print(v)
    print("")

In [4]:
x0 = np.float64(np.array([1,0,0]))
eigenvect, eigenval = power_method(A,x0,n=3,print_everything = True)

iteration:  1
eigenvector:  [ 0.9830783   0.16384638 -0.08192319]
eigenvalue: 
12.0

iteration:  2
eigenvector:  [ 0.94773821  0.29259032 -0.12721318]
eigenvalue: 
12.416666666666666
22.999999999999996
19.999999999999996

iteration:  3
eigenvector:  [ 0.91052941  0.38817306 -0.14233012]
eigenvalue: 
12.751677852348992
17.608695652173914
14.850000000000001



In [5]:
# more iterations to get a better approximation
eigenvect, eigenval = power_method(A,x0,n=200,print_everything = False)
print(eigenvect)
eigenval

[0.45440135 0.76618459 0.45440135]


[14.372281316211613, 14.372281323269014, 14.372281330326414]

In [6]:
# second largest lambda
u1u1T = [ [ eigenvect[i] *eigenvect[j] for j in range(len(eigenvect))] for i in range(len(eigenvect))]
u1u1T

[[0.2064805879320809, 0.34815531353093826, 0.2064805860110756],
 [0.34815531353093826, 0.5870388279778488, 0.3481553102918531],
 [0.2064805860110756, 0.3481553102918531, 0.2064805840900703]]

In [7]:
eigenval1 = eigenval[0]
np.multiply(eigenval,u1u1T)

array([[2.9675971 , 5.00378611, 2.96759707],
       [5.00378611, 8.43708718, 5.00378607],
       [2.96759707, 5.00378606, 2.96759704]])

In [8]:
A_1 = A - np.multiply(eigenval,u1u1T)
A_1

array([[ 9.0324029 , -3.00378611, -3.96759707],
       [-3.00378611,  3.56291282, -3.00378607],
       [-3.96759707, -3.00378606,  9.03240296]])

In [9]:
x0 = np.float64(np.array([1,0,0]))
eigenvect2, eigenval2 = power_method(A_1,x0,n=100,print_everything = False)
eigenval2

[13.0, 13.0, 13.0]