In [1]:
import numpy as np
import numpy.linalg as LA

In [2]:
A = np.array([[12,2,-1],
             [2,12,2],
             [-1,2,12]])
eigenvalues, eigenvectors = LA.eigh(A)
print(eigenvalues)
print(eigenvectors)
eigenvalues.max()

[ 8.62771868 13.         14.37228132]
[[ 5.41774320e-01  7.07106781e-01 -4.54401349e-01]
 [-6.42620551e-01 -1.11022302e-15 -7.66184591e-01]
 [ 5.41774320e-01 -7.07106781e-01 -4.54401349e-01]]


14.372281323269013

In [3]:
def power_method(A, x, n=1, print_everything = True):
    '''Power method for computation of maximum abs(lambda)
        
        Input:
            A nxn matrix
            x starting nx1 vector (x_0)
            n = 1 (default) the maximum number of iterations
            print_everything = True (default) prints status of method in every iteration
        
        Output:
            x normalized eigenvector approximation at the n-iteration
            v the eigenvalue approximation at the n-iternation
    '''
    norm_x = LA.norm(x)
    for k in range(n):
        y = np.matmul(A,x)
        norm_y = LA.norm(y)
        x = (1./norm_y)*y
        v = norm_y/norm_x
        norm_x = LA.norm(x)
        if print_everything: print_power_meth_status(k,x,v)
    return x, v

def print_power_meth_status(k,x,v):
    print("iteration: ", k+1)
    print("eigenvector: ", x)
    print("eigenvalue: ", v)
    print("")

In [4]:
x0 = np.float64(np.array([1,0,0]))
eigenvect, eigenval = power_method(A,x0,n=3,print_everything = True)

iteration:  1
eigenvector:  [ 0.9830783   0.16384638 -0.08192319]
eigenvalue:  12.206555615733702

iteration:  2
eigenvector:  [ 0.94773821  0.29259032 -0.12721318]
eigenvalue:  12.87967026131758

iteration:  3
eigenvector:  [ 0.91052941  0.38817306 -0.14233012]
eigenvalue:  13.272775351135333



In [5]:
#check that A*v = lambda*v and print lambda
print(np.matmul(A,eigenvect))
print(eigenval*eigenvect)
eigenval

[11.84502918  6.19447535 -1.84214477]
[12.08525232  5.15213388 -1.88911576]


13.272775351135333

In [6]:
# more iterations to get a better approximation
eigenvect, eigenval = power_method(A,x0,n=37,print_everything = False)
print(eigenvect)
eigenval

[0.48090712 0.76563272 0.427241  ]


14.369981844407159

In [7]:
# second largest lambda
u1u1T = [ [ eigenvect[i] *eigenvect[j] for j in range(len(eigenvect))] for i in range(len(eigenvect))]
u1u1T

[[0.23127166133154042, 0.3681982311970557, 0.20546323890138893],
 [0.3681982311970557, 0.586193469083502, 0.3271096886836447],
 [0.20546323890138893, 0.3271096886836447, 0.18253486958495765]]

In [8]:
np.multiply(eigenval,u1u1T)

array([[3.32336957, 5.2910019 , 2.95250301],
       [5.2910019 , 8.42358951, 4.70056029],
       [2.95250301, 4.70056029, 2.62302276]])

In [9]:
A_1 = A - np.multiply(eigenval,u1u1T)
A_1

array([[ 8.67663043, -3.2910019 , -3.95250301],
       [-3.2910019 ,  3.57641049, -2.70056029],
       [-3.95250301, -2.70056029,  9.37697724]])

In [10]:
x0 = np.float64(np.array([1,0,0]))
eigenvect2, eigenval2 = power_method(A_1,x0,n=9,print_everything = False)
eigenval2

12.998993824032917