In [1]:
import numpy as np

In [2]:
A = np.array([[12,2,-1],
             [2,12,2],
             [-1,2,12]])
eigenvalues, eigenvectors = np.linalg.eigh(A)
print(eigenvalues)
print(eigenvectors)
eigenvalues.max()

[ 8.62771868 13.         14.37228132]
[[ 5.41774320e-01  7.07106781e-01 -4.54401349e-01]
 [-6.42620551e-01 -1.11022302e-15 -7.66184591e-01]
 [ 5.41774320e-01 -7.07106781e-01 -4.54401349e-01]]


14.372281323269013

In [3]:
def power_method(A, x, n=1, print_everything = True):
    '''Power method for computation of maximum abs(lambda)
        
        Input:
            A nxn matrix
            x starting nx1 vector (x_0)
            n = 1 (default) the maximum number of iterations
            print_everything = True (default) prints status of method in every iteration
        
        Output:
            x normalized eigenvector approximation at the n-iteration
            v the eigenvalue approximation at the n-iternation
    '''
    norm_x = np.linalg.norm(x,np.inf)
    for k in range(n):
        y = np.matmul(A,x)
        norm_y = np.linalg.norm(y,np.inf)
        x = (1./norm_y)*y
        v = norm_y/norm_x
        norm_x = np.linalg.norm(x, np.inf)
        
        if print_everything:
            print_power_meth_status(k,x,v)
    return x, v

def print_power_meth_status(k,x,v):
    print("iteration: ", k+1)
    print("eigenvector: ", x)
    print("eigenvalue: ", v)
    print("")

In [4]:
x0 = np.float64(np.array([1,0,0]))
eigenvect, eigenval = power_method(A,x0,n=3,print_everything = False)

In [5]:
#check that A*v = lambda*v and print lambda
print(np.matmul(A,eigenvect))
print(eigenval*eigenvect)
eigenval

[13.00894737  6.80315789 -2.02315789]
[12.75167785  5.43624161 -1.99328859]


12.751677852348994

In [6]:
# more iterations to get a better approximation
eigenvect, eigenval = power_method(A,x0,n=14,print_everything = True)

iteration:  1
eigenvector:  [ 1.          0.16666667 -0.08333333]
eigenvalue:  12.0

iteration:  2
eigenvector:  [ 1.          0.30872483 -0.13422819]
eigenvalue:  12.416666666666668

iteration:  3
eigenvector:  [ 1.          0.42631579 -0.15631579]
eigenvalue:  12.751677852348994

iteration:  4
eigenvector:  [ 1.          0.52295991 -0.15552049]
eigenvalue:  13.008947368421053

iteration:  5
eigenvector:  [ 1.          0.60330371 -0.13788845]
eigenvalue:  13.201440304244043

iteration:  6
eigenvector:  [ 1.          0.67172771 -0.1085132 ]
eigenvalue:  13.344495862703035

iteration:  7
eigenvector:  [ 1.          0.73176695 -0.0712686 ]
eigenvalue:  13.451968613159975

iteration:  8
eigenvector:  [ 1.          0.78602301 -0.02893942]
eigenvalue:  13.53480250666729

iteration:  9
eigenvector:  [1.         0.83629215 0.01652623]
eigenvalue:  13.600985441880502

iteration:  10
eigenvector:  [1.         0.88375124 0.06377382]
eigenvalue:  13.656058063193042

iteration:  11
eigenvector:  [