In [1]:
import numpy as np
import numpy.linalg as LA

In [2]:
def power_method(A, x, n=1, print_everything = True, rayleigh = False):
    '''Power method for computation of maximum abs(lambda)
        
        Input:
            A nxn matrix
            x starting nx1 vector (x_0)
            n = 1 (default) the maximum number of iterations
            print_everything = True (default) prints status of method in every iteration
            rayleigh = False (default) if True, algorithm uses the Rayleigh quotient for eigenvalue approximation
        
        Output:
            x normalized eigenvector approximation at the n-iteration
            v the eigenvalue approximation at the n-iternation
    '''
    norm_x = LA.norm(x)
    for k in range(n):
        y = np.matmul(A,x)
        norm_y = LA.norm(y)
        x = (1./norm_y)*y
        if rayleigh:
            Ax = np.matmul(A,x)
            v = np.matmul(x,Ax)
        else:       
            v = norm_y/norm_x
        norm_x = LA.norm(x)
        if print_everything: print_power_meth_status(k,x,v)
    return x, v

def print_power_meth_status(k,x,v):
    print("iteration: ", k+1)
    print("eigenvector: ", x)
    print("eigenvalue: ", v)
    print("")

In [3]:
#compute matrix A1 = A - lambda_1 u1 u1^T
A = np.array([[12,2,-1],
             [2,12,2],
             [-1,2,12]])
x0 = np.float64(np.array([1,0,0]))
eigenvect1, eigenval1 = power_method(A,x0,n=37,print_everything = False)
print(eigenvect1)
print(eigenval1)
u1u1T = [ [ eigenvect1[i] *eigenvect1[j] for j in range(len(eigenvect1))] for i in range(len(eigenvect1))]
A_1 = A - np.multiply(eigenval1,u1u1T)
A_1

[0.48090712 0.76563272 0.427241  ]
14.369981844407159


array([[ 8.67663043, -3.2910019 , -3.95250301],
       [-3.2910019 ,  3.57641049, -2.70056029],
       [-3.95250301, -2.70056029,  9.37697724]])

In [4]:
# Eigenvalues for A and A_1
v,w = LA.eigh(A)
print(v)
v1, w1 = LA.eigh(A_1)
v1

[ 8.62771868 13.         14.37228132]


array([1.15087925e-04, 8.62771868e+00, 1.30021844e+01])

In [5]:
eigenvect2, eigenval2 = power_method(A_1,x0,n=5,print_everything = True, rayleigh = False)

iteration:  1
eigenvector:  [ 0.86022463 -0.32627884 -0.39186185]
eigenvalue:  10.086470596588196

iteration:  2
eigenvector:  [ 0.82704747 -0.24103967 -0.50783104]
eigenvalue:  12.195757809749763

iteration:  3
eigenvector:  [ 0.79146485 -0.17552044 -0.58547073]
eigenvalue:  12.605046187949304

iteration:  4
eigenvector:  [ 0.76136837 -0.12883369 -0.63538972]
eigenvalue:  12.817660023154385

iteration:  5
eigenvector:  [ 0.73856742 -0.09679756 -0.66719442]
eigenvalue:  12.918906729064656



In [6]:
eigenvect2_rayl, eigenval2_rayl = power_method(A_1,x0,n=5,print_everything = True, rayleigh = True)

iteration:  1
eigenvector:  [ 0.86022463 -0.32627884 -0.39186185]
eigenvalue:  12.062730787206174

iteration:  2
eigenvector:  [ 0.82704747 -0.24103967 -0.50783104]
eigenvalue:  12.532020030802112

iteration:  3
eigenvector:  [ 0.79146485 -0.17552044 -0.58547073]
eigenvalue:  12.781915698476858

iteration:  4
eigenvector:  [ 0.76136837 -0.12883369 -0.63538972]
eigenvalue:  12.902385152128595

iteration:  5
eigenvector:  [ 0.73856742 -0.09679756 -0.66719442]
eigenvalue:  12.957673359858777



In [7]:
# comparison
print("n=1")
eigenvect2, eigenval2 = power_method(A_1,x0,n=1,print_everything = False, rayleigh = True)
print("Rayleigh",eigenval2)
eigenvect2, eigenval2 = power_method(A_1,x0,n=1,print_everything = False, rayleigh = False)
print("simple",eigenval2)
print("n=2")
eigenvect2, eigenval2 = power_method(A_1,x0,n=2,print_everything = False, rayleigh = True)
print("Rayleigh",eigenval2)
eigenvect2, eigenval2 = power_method(A_1,x0,n=2,print_everything = False, rayleigh = False)
print("simple",eigenval2)

n=1
Rayleigh 12.062730787206174
simple 10.086470596588196
n=2
Rayleigh 12.532020030802112
simple 12.195757809749763
